# Stable generated bytes across Ruby JSON versions and execution dates.
# Version-Timestamp: 2026-09-15 21:58:41 AST
require 'json'
require 'date'

module GeneratedOutput
  def self.json(value)
    JSON.pretty_generate(value).gsub(/\[\n\s*\]/, '[]').gsub(/\{\n\s*\}/, '{}')
  end

  def self.date(manifest)
    Date.iso8601(manifest.fetch('generated_at', Date.today.iso8601)).iso8601
  end
end
