#!/usr/bin/env ruby
# Generate a source-organized index for the skill library without changing the
# canonical Agent Skills layout at skills/<skill-name>/SKILL.md.

require "fileutils"
require "json"
require "uri"
require "yaml"

ROOT = File.expand_path("..", __dir__)
SKILLS_DIR = File.join(ROOT, "skills")
SOURCES_DIR = File.join(ROOT, "sources")
MANIFEST_PATH = File.join(ROOT, "manifests", "skills-manifest.json")
SOURCE_DOC_PATH = File.join(ROOT, "docs", "SKILL-SOURCES.md")
GENERATED_MARKER = ".generated-source-index"

def read_frontmatter(path)
  text = File.read(path)
  frontmatter = text.split(/^---\s*$/, 3)[1]
  YAML.safe_load(frontmatter, aliases: true) || {}
rescue StandardError => error
  warn "Could not parse #{path}: #{error.message}"
  {}
end

def normalize_source(raw_source)
  source = raw_source.to_s.strip
  source = "original" if source.empty?
  note = nil

  if source == "original"
    return {
      "slug" => "original",
      "label" => "Original New Minds Group",
      "repository" => "Original New Minds Group",
      "url" => nil,
      "type" => "original",
      "note" => "Skills created directly in this library."
    }
  end

  if source == "https://github.com/menkesu/awesome-pm-skills and skills CLI installs"
    source = "https://github.com/menkesu/awesome-pm-skills"
    note = "Imported from the repository and related skills CLI install output."
  end

  if source == "OpenAI Codex bundled system skills"
    return {
      "slug" => "openai-codex-bundled-system-skills",
      "label" => "OpenAI Codex bundled system skills",
      "repository" => source,
      "url" => nil,
      "type" => "runtime",
      "note" => "Bundled with the local Codex runtime rather than imported from a public repo."
    }
  end

  begin
    uri = URI.parse(source)
    if uri.host == "github.com"
      parts = uri.path.sub(%r{\A/}, "").sub(/\.git\z/, "").split("/")
      owner, repo = parts[0], parts[1]
      if owner && repo
        return {
          "slug" => "#{owner}-#{repo}".downcase.gsub(/[^a-z0-9]+/, "-").gsub(/\A-|-+\z/, ""),
          "label" => "#{owner}/#{repo}",
          "repository" => "https://github.com/#{owner}/#{repo}",
          "url" => "https://github.com/#{owner}/#{repo}",
          "type" => "github",
          "note" => note
        }
      end
    end
  rescue URI::InvalidURIError
    # Fall through to generic source handling.
  end

  label = source
  {
    "slug" => label.downcase.gsub(/[^a-z0-9]+/, "-").gsub(/\A-|-+\z/, ""),
    "label" => label,
    "repository" => label,
    "url" => source.start_with?("http") ? source : nil,
    "type" => "other",
    "note" => note
  }
end

def markdown_escape(value)
  value.to_s.gsub("\n", " ").gsub("|", "\\|").strip
end

def load_manifest_categories
  return {} unless File.exist?(MANIFEST_PATH)

  manifest = JSON.parse(File.read(MANIFEST_PATH))
  manifest.fetch("skills", []).to_h { |entry| [entry["name"], entry["category"]] }
end

categories = load_manifest_categories
skills = Dir.glob(File.join(SKILLS_DIR, "*", "SKILL.md")).sort.map do |path|
  folder = File.basename(File.dirname(path))
  frontmatter = read_frontmatter(path)
  metadata = frontmatter.fetch("metadata", {}) || {}
  source = normalize_source(metadata["source_repository"])

  {
    "name" => folder,
    "description" => frontmatter["description"].to_s.strip,
    "category" => categories[folder] || "Uncategorized",
    "path" => "skills/#{folder}/",
    "source_path" => metadata["source_path"],
    "source" => source
  }
end

grouped = skills.group_by { |skill| skill["source"]["slug"] }
source_rows = grouped.map do |slug, entries|
  source = entries.first["source"]
  source.merge("slug" => slug, "count" => entries.length)
end.sort_by { |entry| [-entry["count"], entry["slug"]] }

if File.exist?(SOURCES_DIR)
  marker = File.join(SOURCES_DIR, GENERATED_MARKER)
  abort "Refusing to overwrite non-generated #{SOURCES_DIR}" unless File.exist?(marker)
end

FileUtils.rm_rf(SOURCES_DIR)
FileUtils.mkdir_p(SOURCES_DIR)
File.write(File.join(SOURCES_DIR, GENERATED_MARKER), "Generated by scripts/generate-source-index.rb\n")

source_index = []
source_index << "# Skills by Source"
source_index << ""
source_index << "This directory organizes the library by where each skill came from."
source_index << ""
source_index << "The folders here are human-readable provenance indexes. The canonical loadable skills stay in `../skills/<skill-name>/SKILL.md` because the Agent Skills spec, validators, installers, and IDE adapters expect that flat layout."
source_index << ""
source_index << "| Source folder | Source | Type | Skills |"
source_index << "|---|---|---|---:|"

source_rows.each do |source|
  folder = source["slug"]
  label = source["url"] ? "[#{markdown_escape(source["label"])}](#{source["url"]})" : markdown_escape(source["label"])
  source_index << "| [`#{folder}`](#{folder}/) | #{label} | #{source["type"]} | #{source["count"]} |"

  entries = grouped.fetch(folder).sort_by { |skill| skill["name"] }
  source_dir = File.join(SOURCES_DIR, folder)
  FileUtils.mkdir_p(source_dir)

  lines = []
  lines << "# #{source["label"]}"
  lines << ""
  lines << "- Source folder: `sources/#{folder}/`"
  lines << "- Source type: `#{source["type"]}`"
  lines << "- Skill count: #{entries.length}"
  lines << "- Repository: #{source["url"] ? "[#{source["repository"]}](#{source["url"]})" : source["repository"]}"
  lines << "- Note: #{source["note"]}" if source["note"] && !source["note"].empty?
  lines << ""
  lines << "Canonical skill folders remain under `../../skills/`."
  lines << ""
  lines << "## Skills"
  lines << ""
  lines << "| Skill | Category | Description | Source path |"
  lines << "|---|---|---|---|"
  entries.each do |skill|
    source_path = skill["source_path"] ? "`#{markdown_escape(skill["source_path"])}`" : ""
    lines << "| [`#{skill["name"]}`](../../#{skill["path"]}) | #{markdown_escape(skill["category"])} | #{markdown_escape(skill["description"])} | #{source_path} |"
  end

  File.write(File.join(source_dir, "README.md"), lines.join("\n") + "\n")
end

File.write(File.join(SOURCES_DIR, "README.md"), source_index.join("\n") + "\n")

if File.exist?(MANIFEST_PATH)
  manifest = JSON.parse(File.read(MANIFEST_PATH))
  source_by_name = skills.to_h { |skill| [skill["name"], skill] }
  manifest["source_groups"] = source_rows
  manifest["skills"].each do |entry|
    skill = source_by_name[entry["name"]]
    next unless skill

    source = skill["source"]
    entry["source_repository"] = source["repository"]
    entry["source_slug"] = source["slug"]
    entry["source_label"] = source["label"]
    entry["source_type"] = source["type"]
    entry["source_path"] = skill["source_path"] if skill["source_path"]
    entry["source_note"] = source["note"] if source["note"] && !source["note"].empty?
  end
  File.write(MANIFEST_PATH, JSON.pretty_generate(manifest) + "\n")
end

doc = []
doc << "# Skill Sources"
doc << ""
doc << "Generated source map for every skill in the repository."
doc << ""
doc << "Canonical loadable skills remain in `skills/<skill-name>/`. Source-organized provenance folders live in [`../sources/`](../sources/)."
doc << ""
doc << "## Source Groups"
doc << ""
doc << "| Source folder | Source | Type | Skills |"
doc << "|---|---|---|---:|"
source_rows.each do |source|
  label = source["url"] ? "[#{markdown_escape(source["label"])}](#{source["url"]})" : markdown_escape(source["label"])
  doc << "| [`#{source["slug"]}`](../sources/#{source["slug"]}/) | #{label} | #{source["type"]} | #{source["count"]} |"
end

manifest = File.exist?(MANIFEST_PATH) ? JSON.parse(File.read(MANIFEST_PATH)) : {}
duplicates = manifest.fetch("duplicate_source_names", {})
unless duplicates.empty?
  doc << ""
  doc << "## Duplicate Source Names Resolved"
  doc << ""
  doc << "When the same skill name appeared in multiple local source roots, the canonical `skills/<name>/` copy was kept and the other copies are listed below."
  doc << ""
  duplicates.sort.each do |name, copies|
    details = copies.map { |copy| "#{copy["source"]}:`#{copy["path"]}`" }.join(", ")
    doc << "- `#{name}`: #{details}"
  end
end

doc << ""
doc << "## Machine-Readable Manifest"
doc << ""
doc << "See [`../manifests/skills-manifest.json`](../manifests/skills-manifest.json). Each skill entry now includes `source_slug`, `source_label`, `source_type`, and `source_path` when available."
File.write(SOURCE_DOC_PATH, doc.join("\n") + "\n")

puts "Generated #{source_rows.length} source folder(s) for #{skills.length} skill(s)."
source_rows.each { |source| puts "#{source["count"]}\t#{source["slug"]}\t#{source["label"]}" }
